channels:
  - conda-forge
  - esrf-bcu
dependencies:
  - numpy
  - pandas
  - matplotlib
  - dask
  - python-graphviz
  - scikit-learn
  - awkward
  - uproot
  - numba
  - cython
  - pybind11
  - pillow
  - libnuma
  - psutil
